### ISSUE TITLE
TypeError: __init__() got multiple values for keyword argument 'asin'

### ISSUE THREAD

**Issue by shimizurei** [elarkham/VGMdb-BeetsPlug#4]
I know you said you don't use beets much anymore, but maybe this can be figured out just from the error code?

Here is my new fork: [Shimibranch](https://github.com/shimizurei/VGMdb-BeetsPlug/blob/shimiversion/vgmdb.py)

**Problem**
```
PS C:\Users\ME> beet -v import C:\Users\ME\Downloads\Muzik\[TESTOO]\why4
user configuration: C:\Users\ME\AppData\Roaming\beets\config.yaml
data directory: C:\Users\ME\AppData\Roaming\beets
plugin paths: C:\Users\ME\AppData\Roaming\beets\beetsplug
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
Querying VGMdb 1.1.0
inline: adding item field multidisc
inline: adding album field grouped
library database: C:\Users\ME\AppData\Roaming\beets\beets_musiclibrary.db
library directory: C:\Users\ME\Music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_start
Looking up: C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\01 - Good Morning.mp3; C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\02 - Art School.mp3; C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\03 - fan fan fan.mp3; C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\04 - Friend.mp3; C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\05 - Sad Song.mp3; C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\06 - Seventh Heaven.mp3; C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\07 - Lotus Heaven.mp3; C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\08 - Trip Trap Drop.mp3; C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\09 - Guitar & Cigarette.mp3; C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\10 - Memories.mp3
Tagging Hasegawa Tomoki - NANA 7to8 soundtracks
No album ID found.
Search terms: Hasegawa Tomoki - NANA 7to8 soundtracks
Album might be VA: False
Searching for MusicBrainz releases with: {'release': u'nana 7to8 soundtracks', 'tracks': u'10', 'artist': u'hasegawa tomoki'}
Requesting MusicBrainz release bcc9aabe-9560-4ef8-93e2-a3ca85a3d963
primary MB release type: album
secondary MB release type(s): soundtrack
Sending event: albuminfo_received
Candidate: Θò╖Φ░╖σ╖¥µÖ║µ¿╣ - NANA 7to8 soundtracks (bcc9aabe-9560-4ef8-93e2-a3ca85a3d963)
Computing track assignment...
...done.
Success. Distance: 0.09
Requesting MusicBrainz release e58c5387-a389-484a-a35d-1c93b871c3ed
primary MB release type: album
secondary MB release type(s): soundtrack
Sending event: albuminfo_received
Candidate: Θò╖Φ░╖σ╖¥µÖ║µ¿╣ - NANA 7to8 soundtracks (e58c5387-a389-484a-a35d-1c93b871c3ed)
Computing track assignment...
...done.
Success. Distance: 0.09
Requesting MusicBrainz release 89a2d9cc-1ff8-4dde-9d4f-86de6965c866
primary MB release type: album
secondary MB release type(s): soundtrack
Sending event: albuminfo_received
Candidate: Θò╖Φ░╖σ╖¥µÖ║µ¿╣ - DearS: TV Animation Original Soundtrack (89a2d9cc-1ff8-4dde-9d4f-86de6965c866)
Computing track assignment...
...done.
Success. Distance: 0.85
Requesting MusicBrainz release 3ede27b5-7b1d-4358-b716-c9fb3ad387f2
primary MB release type: album
secondary MB release type(s): soundtrack
Sending event: albuminfo_received
Candidate: Θò╖Φ░╖σ╖¥µÖ║µ¿╣ - Sayonara Zetsubou Sensei OST (3ede27b5-7b1d-4358-b716-c9fb3ad387f2)
Computing track assignment...
...done.
Success. Distance: 0.85
Requesting MusicBrainz release 7aa8e809-d9ae-4b9c-af46-fbbaca4a697d
primary MB release type: album
secondary MB release type(s): soundtrack
Sending event: albuminfo_received
Candidate: Θò╖Φ░╖σ╖¥µÖ║µ¿╣ - NANA 707 Soundtracks (7aa8e809-d9ae-4b9c-af46-fbbaca4a697d)
Computing track assignment...
...done.
Success. Distance: 0.84
get_albums Querying VGMdb for release Hasegawa Tomoki NANA 7to8 soundtracks
discogs: Searching for master release 1119316
discogs: Searching for master release 1119316
Sending event: albuminfo_received
Candidate: Tomoki Hasegawa - Nana 7 To 8 Soundtracks (6683260)
Computing track assignment...
...done.
Success. Distance: 0.13
Sending event: albuminfo_received
Candidate: Tomoki Hasegawa - Nana 7 To 8 Soundtracks (9667857)
Computing track assignment...
...done.
Success. Distance: 0.13
Evaluating 7 candidates.

C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\01 - Good Morning.mp3
C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\02 - Art School.mp3
C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\03 - fan fan fan.mp3
C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\04 - Friend.mp3
C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\05 - Sad Song.mp3
C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\06 - Seventh Heaven.mp3
C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\07 - Lotus Heaven.mp3
C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\08 - Trip Trap Drop.mp3
C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\09 - Guitar & Cigarette.mp3
C:\Users\ME\Downloads\Muzik\[TESTOO]\why4\[2006] NANA 7to8 soundtracks_VPCG-84838\10 - Memories.mp3 (10 items)
Sending event: before_choose_candidate
Correcting tags from:
    Hasegawa Tomoki - NANA 7to8 soundtracks
To:
    Θò╖Φ░╖σ╖¥µÖ║µ¿╣ - NANA 7to8 soundtracks
URL:
    https://musicbrainz.org/release/e58c5387-a389-484a-a35d-1c93b871c3ed
(Similarity: 91.4%) (artist) (CD, 2007, JP, vap)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? m
Finding tags for album "Hasegawa Tomoki - NANA 7to8 soundtracks".
Candidates:
1. Θò╖Φ░╖σ╖¥µÖ║µ¿╣ - NANA 7to8 soundtracks (91.4%) (artist) (CD, 2007, JP, vap)
2. Θò╖Φ░╖σ╖¥µÖ║µ¿╣ - NANA 7to8 soundtracks (91.4%) (artist) (2006, US)
3. Tomoki Hasegawa - Nana 7 To 8 Soundtracks (87.0%) (artist, source, year) (Discogs, CD, 2008, France, Wasabi Records (2))
4. Tomoki Hasegawa - Nana 7 To 8 Soundtracks (87.0%) (artist, source, year) (Discogs, CD, 2008, Unknown, Miya Records)
5. Θò╖Φ░╖σ╖¥µÖ║µ¿╣ - NANA 707 Soundtracks (15.5%) (missing tracks, tracks, artist, ...) (CD, 2006, JP, vap)
6. Θò╖Φ░╖σ╖¥µÖ║µ¿╣ - Sayonara Zetsubou Sensei OST (15.5%) (missing tracks, tracks, artist, ...) (CD, 2007, JP)
7. Θò╖Φ░╖σ╖¥µÖ║µ¿╣ - DearS: TV Animation Original Soundtrack (15.1%) (missing tracks, tracks, artist, ...) (CD, 2006, US, Geneon)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? i
Enter release ID: 58215
Tagging Hasegawa Tomoki - NANA 7to8 soundtracks
Searching for album ID: 58215
Requesting MusicBrainz release 58215
Invalid MBID (58215).
Querying VGMdb for release 58215
Traceback (most recent call last):
  File "C:\Python27\Scripts\beet-script.py", line 11, in <module>
    load_entry_point('beets==1.4.7', 'console_scripts', 'beet')()
  File "c:\python27\lib\site-packages\beets\ui\__init__.py", line 1256, in main
    _raw_main(args)
  File "c:\python27\lib\site-packages\beets\ui\__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "c:\python27\lib\site-packages\beets\ui\commands.py", line 943, in import_func
    import_files(lib, paths, query)
  File "c:\python27\lib\site-packages\beets\ui\commands.py", line 913, in import_files
    session.run()
  File "c:\python27\lib\site-packages\beets\importer.py", line 329, in run
    pl.run_parallel(QUEUE_SIZE)
  File "c:\python27\lib\site-packages\beets\util\pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "c:\python27\lib\site-packages\beets\util\pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "c:\python27\lib\site-packages\beets\util\pipeline.py", line 171, in coro
    task = func(*(args + (task,)))
  File "c:\python27\lib\site-packages\beets\importer.py", line 1375, in user_query
    task.choose_match(session)
  File "c:\python27\lib\site-packages\beets\importer.py", line 838, in choose_match
    choice = session.choose_match(self)
  File "c:\python27\lib\site-packages\beets\ui\commands.py", line 713, in choose_match
    post_choice = choice.callback(self, task)
  File "c:\python27\lib\site-packages\beets\ui\commands.py", line 658, in manual_id
    task.items, search_ids=search_id.split()
  File "c:\python27\lib\site-packages\beets\autotag\match.py", line 424, in tag_album
    for id_candidate in hooks.albums_for_id(search_id):
  File "c:\python27\lib\site-packages\beets\autotag\hooks.py", line 568, in albums_for_id
    for a in plugins.album_for_id(album_id):
  File "c:\python27\lib\site-packages\beets\plugins.py", line 387, in album_for_id
    album = plugin.album_for_id(album_id)
  File "C:\Users\ME\AppData\Roaming\beets\beetsplug\vgmdb3.py", line 64, in album_for_id
    return self.get_album_info(item, False)
  File "C:\Users\ME\AppData\Roaming\beets\beetsplug\vgmdb3.py", line 266, in get_album_info
    catalognum=self.decod(catalognum)
TypeError: __init__() got multiple values for keyword argument 'asin'
```

**What I tried:**

Commenting out asin and albumtype stops the error, but the program doesn't seem to detect the script much afterwards.

I swapped in your original script and there was no problem. I don't understand what is causing the multiple values, considering I don't assign a single thing to "asin" or "albumtype". The biggest change in my changes versus your original are the track names additions.

I hope you don't mind taking a glance and helping me figure out what's going on?

**Comment by elarkham** [comment]
This is because you are not properly filling the parameters of the AlbumInfo constructor. It will make more sense if you take a look at the AlbumInfo class's code [here](https://github.com/beetbox/beets/blob/master/beets/autotag/hooks.py). As a small tip, whenever you are making a plugin for something it's always a good idea to look at the source code of the main program if available, being familiar with the API is always an important first step for this kind of thing.

**Comment by shimizurei** [comment]
It's because I added that `lyricist` part when there is no mention of a lyricist in the original `AlbumInfo`, isn't it?

**Comment by elarkham** [comment]
Yes

**Comment by shimizurei** [comment]
Then, I guess I'll be adding the lyricist in post then.

Thanks for the help :)
